// src/features/cart/cartSlice.js

/**
 * 🎯 CART SLICE - Manages shopping cart state
 *
 * This file replaces THREE files from old Redux:
 * 1. constants/cartConstants.js
 * 2. actions/cartAction.js
 * 3. reducers/cartReducer.js
 *
 * Redux Toolkit combines everything into ONE file called a "slice"
 */

// 📦 Import dependencies
import { createSlice } from "@reduxjs/toolkit";

/**
 * 🏪 Initial State - What's in our cart when app starts?
 *
 * We load from localStorage so items persist after page refresh
 * This is like having a "memory" for the cart
 */
const initialState = {
  // Load cart items from localStorage or start empty
  cartItems: localStorage.getItem("cartItems")
    ? JSON.parse(localStorage.getItem("cartItems"))
    : [],

  // Load shipping info from localStorage or start empty
  shippingInfo: localStorage.getItem("shippingInfo")
    ? JSON.parse(localStorage.getItem("shippingInfo"))
    : {},
};

/**
 * 🎨 Create the Cart Slice
 *
 * Think of createSlice as a factory that makes:
 * 1. Actions (like "ADD_TO_CART")
 * 2. Reducers (how to handle those actions)
 * 3. Selectors (how to get data from the state)
 *
 * All in one place!
 */
const cartSlice = createSlice({
  name: "cart", // This becomes the action prefix: 'cart/addToCart'
  initialState, // Our initial state defined above
  reducers: {
    /**
     * ➕ ADD TO CART
     *
     * @param {Object} state - Current cart state (can mutate directly!)
     * @param {Object} action - Contains the item to add
     *
     * WHY CAN WE MUTATE STATE DIRECTLY?
     * Redux Toolkit uses Immer internally. It lets us write "mutating" code
     * but actually creates immutable updates behind the scenes.
     * No more spread operators everywhere! 🎉
     */
    addToCart: (state, action) => {
      // Get the item we want to add
      const item = action.payload;

      // Check if this product already exists in cart
      const isItemExist = state.cartItems.find(
        (i) => i.product === item.product,
      );

      if (isItemExist) {
        // ✅ Product exists - Update quantity
        // Map through cart items, replace the existing one with the new item
        state.cartItems = state.cartItems.map((i) =>
          i.product === isItemExist.product ? item : i,
        );
      } else {
        // ✅ Product doesn't exist - Add new item
        // Push is allowed with Immer! (mutating syntax)
        state.cartItems.push(item);
      }

      // 💾 Save to localStorage so it persists
      localStorage.setItem("cartItems", JSON.stringify(state.cartItems));
    },

    /**
     * ❌ REMOVE FROM CART
     *
     * @param {Object} state - Current cart state
     * @param {Object} action - Contains the product ID to remove
     */
    removeFromCart: (state, action) => {
      // Filter out the item with matching product ID
      state.cartItems = state.cartItems.filter(
        (i) => i.product !== action.payload,
      );

      // 💾 Update localStorage
      localStorage.setItem("cartItems", JSON.stringify(state.cartItems));
    },

    /**
     * 📦 SAVE SHIPPING INFO
     *
     * @param {Object} state - Current cart state
     * @param {Object} action - Contains shipping address data
     */
    saveShippingInfo: (state, action) => {
      // Update shipping info
      state.shippingInfo = action.payload;

      // 💾 Save to localStorage
      localStorage.setItem("shippingInfo", JSON.stringify(action.payload));
    },

    /**
     * 🗑️ CLEAR CART (for after order is placed)
     */
    clearCart: (state) => {
      // Empty the cart
      state.cartItems = [];
      // Remove from localStorage
      localStorage.removeItem("cartItems");
    },
  },
});

/**
 * 📤 EXPORT ACTIONS
 *
 * These are the "action creators" we use in components
 * Example: dispatch(addToCart(product))
 */
export const { addToCart, removeFromCart, saveShippingInfo, clearCart } =
  cartSlice.actions;

/**
 * 📤 EXPORT SELECTORS
 *
 * Selectors are functions that extract specific data from the state
 * We use them with useSelector in components
 */
export const selectCartItems = (state) => state.cart.cartItems;
export const selectShippingInfo = (state) => state.cart.shippingInfo;

/**
 * 📤 EXPORT REDUCER
 *
 * This goes into the store
 * It's automatically generated by createSlice
 */
export default cartSlice.reducer;
